export const siteContent = {
  brand: {
    name: 'Senty',
    logoSrc: `${import.meta.env.BASE_URL}senty-logo.svg`,
  },
  nav: {
    links: [
      { label: 'Metodo', href: '#metodo' },
      { label: 'Insight', href: '#insight' },
      { label: 'Perché Senty', href: '#perche-senty' },
    ],
    cta: { label: 'Richiedi una demo', href: '#demo' },
  },
  hero: {
    eyebrow: 'SENTIMENT INTELLIGENCE',
    title: ['Capisci cosa sentono', 'le persone.', 'E cosa farne.'],
    body: 'Senty raccoglie feedback, recensioni e conversazioni e li trasforma in segnali chiari, confrontabili e pronti per diventare decisioni.',
    primaryCta: { label: 'Richiedi una demo', href: '#demo' },
    secondaryCta: { label: 'Scopri come funziona', href: '#metodo' },
  },
  heroSignals: [
    { source: 'Google', quote: 'Prodotto ottimo, consegna lenta.', sentiment: 'Misto' },
    { source: 'Instagram', quote: 'Esperienza super intuitiva ✨', sentiment: 'Positivo' },
    { source: 'Survey', quote: 'Vorrei tempi di risposta più rapidi.', sentiment: 'Negativo' },
  ],
  insight: {
    label: 'Senty ha trovato un pattern',
    title: 'Il servizio sta diventando il principale driver del sentiment.',
    meta: '+18% menzioni nelle ultime 4 settimane',
  },
  method: {
    eyebrow: 'IL METODO SENTY',
    title: 'Dal rumore a una decisione.',
    intro: 'Cinque passaggi, un solo flusso. Ogni scroll porta più chiarezza: dalle voci sparse a una prossima mossa concreta.',
    steps: [
      {
        id: 'raccogli',
        number: '01',
        title: 'Raccogli',
        body: 'Recensioni, survey, commenti e feedback entrano nello stesso spazio. Le fonti restano riconoscibili, ma smettono di vivere isolate.',
        note: 'Tutte le voci, nello stesso posto.',
        visual: 'collect',
        image: 'https://raw.githubusercontent.com/SabRo11/Senty/main/public/raccogli.jpg',
      },
      {
        id: 'analizza',
        number: '02',
        title: 'Analizza',
        body: 'L’AI classifica temi, sentiment e ricorrenze. Il volume diventa struttura e le conversazioni iniziano a mostrare pattern leggibili.',
        note: 'Il caos prende una forma.',
        visual: 'analyze',
        image: 'https://raw.githubusercontent.com/SabRo11/Senty/main/public/analizza.jpg',
      },
      {
        id: 'comprendi',
        number: '03',
        title: 'Comprendi',
        body: 'Senty collega i segnali e mette in evidenza ciò che sta davvero muovendo la percezione delle persone, anche quando il segnale è ancora piccolo.',
        note: 'Non solo cosa succede. Perché.',
        visual: 'understand',
        image: 'https://raw.githubusercontent.com/SabRo11/Senty/main/public/comprendi.jpg',
      },
      {
        id: 'confronta',
        number: '04',
        title: 'Confronta',
        body: 'Periodi, canali, temi e benchmark diventano confrontabili. Capisci cosa sta migliorando, cosa sta peggiorando e dove cambia il contesto.',
        note: 'Un segnale conta quando ha un contesto.',
        visual: 'compare',
        image: 'https://raw.githubusercontent.com/SabRo11/Senty/main/public/confronta.jpg',
      },
      {
        id: 'restituisci',
        number: '05',
        title: 'Restituisci',
        body: 'Gli insight diventano priorità chiare, condivisibili e pronte per l’azione. Meno dashboard da interpretare, più prossime mosse da discutere.',
        note: 'Dall’insight alla prossima decisione.',
        visual: 'return',
        image: 'https://raw.githubusercontent.com/SabRo11/Senty/main/public/restituisci.jpg',
      },
    ],
  },
} as const
